# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 23:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_name', models.CharField(max_length=200)),
                ('quest_type', models.CharField(choices=[('STORY', 'Main Story Quest'), ('SIDE', 'Side Quest'), ('SHRINE', 'Shrine Quest')], default='STORY', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QuestEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovery_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField()),
                ('quest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quests.Quest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
