# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questentry',
            name='quest',
        ),
        migrations.RemoveField(
            model_name='questentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='QuestEntry',
        ),
    ]
